#!/bin/bash

TOOLS="$( cd "$( dirname "$0" )" && pwd )"
VENV_DIR=$TOOLS/../.venv

rm -rf $VENV_DIR

echo -n "Creating venv..."
virtualenv --no-site-packages -q $VENV_DIR || exit
echo "ok"

echo -n "Installing pip in venv..."
$VENV_DIR/bin/easy_install pip > /dev/null || exit
echo "ok"

echo -n "Installing modules in pip-requires..."
$VENV_DIR/bin/pip install -E $VENV_DIR -r $TOOLS/pip-requires > /dev/null || exit
echo "ok"
