#!/bin/bash
DIR="$( cd "$( dirname "$0" )" && pwd )"

export PYTHONPATH="$PYTHONPATH:$DIR/..:$DIR/../src"

# Checking source
pylint --rcfile=$DIR/pylintrc openstack.common

# Checking tests
pylint --rcfile=$DIR/pylintrc tests
