#!/bin/bash
DIR="$( cd "$( dirname "$0" )" && pwd )"

# Checking source
export PYTHONPATH="$DIR/../src"
pylint --rcfile=tools/pylintrc openstack.common

# Checking tests
export PYTHONPATH="$DIR/..:$DIR/../src"
pylint --rcfile=tools/pylintrc tests
