#!/usr/bin/env python

# Copyright 2011 OpenStack, LLC
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

import os
import sys


def main():
    test_directory = os.path.abspath("%s/../.." % __file__)
    common_directory = os.path.abspath("%s/../../src/" % __file__)

    # It kills me to do this, but there is a chicken vs. egg scenario here:
    #     1) openstack.common.testing:TestRunner (for pretty tests)
    #     2) The OpenStack Common project's test suite should use itself
    sys.path.append(common_directory)

    import openstack.common.testing
    test_runner = openstack.common.testing.TestRunner()
    return not test_runner.run(test_directory, argv=sys.argv)


if __name__ == '__main__':
    sys.exit(main())
